spring:
  profiles:
    active: local
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: mk123654
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
    show-sql: true
  kafka:
    topic: "library-events"
    consumer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: library-events-listener-group
---
spring:
  config:
    activate:
      on-profile: nonprod
  kafka:
    producer:
      bootstrap-servers: nonprod:9092,nonprod:9093,nonprod:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

