version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'

  mysql-db:
    image: mysql
    container_name: post-article-mysql-container
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mk123654
      MYSQL_DATABASE: kafka_db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql/

volumes:
  mysql-data:
